name: pxc
version: ${version}
author: Natalie Dessi
main: de.natalie.pxc.Plugin
api-version: '1.20'

commands:
  spawn:
    description: Teleports the current player to the spawn
  home:
    usage: "/home [set | get]"
    description: Sets a home or teleports the player to it's home. [/home get, /home set, /home]

libraries:
  - com.fasterxml.jackson.core:jackson-core:${jacksonVersion}
  - com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}

