name: pxc
version: ${version}
author: Natalie Dessi
main: de.natalie.pxc.Plugin
api-version: '1.20'

commands:
  spawn:
    description: Teleports the current player to the spawn
  home:
    usage: "ยง3/home [set, get]"
    description: Sets a home or teleports the player to it's home.
  color:
    usage: "ยง3/color [set r g b]"
    description: Sets a player color or displays the color

libraries:
  - com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}

